apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: auth-api
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
          resources:
            requests:
              cpu: "300m"
              memory: "384Mi"
            limits:
              cpu: "700m"
              memory: "512Mi"