apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-db-secret
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: auth-db-secret

  data:
    - secretKey: ConnectionStrings__Default
      remoteRef:
        key: staging/auth-task
        property: ConnectionStrings__Default
    
    - secretKey: JwtConfig__SecretKey
      remoteRef:
        key: staging/auth-task
        property: JwtConfig__SecretKey

    - secretKey: ApiKey
      remoteRef:
        key: staging/auth-task
        property: ApiKey